# Generated by Django 4.2.5 on 2023-09-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
